CS3219-AY2425S1/cs3219-ay2425s1-project-g36

README.md
=> README.md: Change Gxx -> G36

frontend/README.md, frontend/package.json, frontend/src/App.tsx, frontend/src/api/question-service/Question.ts, frontend/src/api/question-service/QuestionService.ts, frontend/src/components/common/PageAccountNav.tsx, frontend/src/components/common/PageHeader.tsx, frontend/src/components/question-service/Difficulty.tsx, frontend/src/components/question-service/list-question-page/FilterPopover.tsx, frontend/src/components/question-service/list-question-page/ListQuestionTable.tsx, frontend/src/components/question-service/list-question-page/TopicView.tsx, frontend/src/components/ui/SearchInput.tsx, frontend/src/components/ui/avatar.tsx, frontend/src/components/ui/badge.tsx, frontend/src/components/ui/checkbox.tsx, frontend/src/components/ui/dropdown-menu.tsx, frontend/src/components/ui/form.tsx, frontend/src/components/ui/input.tsx, frontend/src/components/ui/label.tsx, frontend/src/components/ui/popover.tsx, frontend/src/components/ui/table.tsx, frontend/src/index.css, frontend/src/pages/question-service/ListQuestionPage.tsx, frontend/tailwind.config.js, frontend/yarn.lock, question-service/package-lock.json, question-service/package.json, question-service/src/index.ts
Fixes #9.
Design should be ok already, but please review and give your feedback on what aspects of the code may be unclear since there is quite a lot of implementation details I needed to do to implement the page
Can be accessed through http://localhost:5173/questions as long as you have the question service http://localhost:3000 running
Changes:
- Implement Question List Page, question deletion, search and filter
- Implement PeerPrep page header, account logout functionality
- Set default page when logged in to be the Question List Page
What works:
- Questions from the backend
- Search functionality (with a few search filters, please come up with more suggestions if required thanks)
- **Backend change:** Added CORS header to ensure the frontend-backend connection works
- Deletion of …
=> Add design for question list

frontend/src/api/question-service/QuestionService.ts, frontend/src/components/question-service/Difficulty.tsx, frontend/src/pages/question-service/ViewQuestionPage.tsx
as per title. looks bussing thanks v0
=> Add ViewQuestionPage and made Difficulty component look nicer

frontend/src/api/question-service/QuestionService.ts, question-service/src/routes/questionsRoute.ts
1. Add endpoint to GET question topics
2. Add error handling for duplicate question title when doing a POST/PUT request
=> Add get-topics endpoint

frontend/package.json, frontend/src/api/question-service/Question.ts, frontend/src/api/question-service/QuestionService.ts, frontend/src/components/common/MainContainer.tsx, frontend/src/components/common/PageTitle.tsx, frontend/src/components/question-service/DifficultyEdit.tsx, frontend/src/components/question-service/QuestionInputField.tsx, frontend/src/components/question-service/edit-question-page/EditQuestionForm.tsx, frontend/src/components/question-service/edit-question-page/QuestionInputField.tsx, frontend/src/components/question-service/edit-question-page/QuestionSelectField.tsx, frontend/src/components/question-service/edit-question-page/QuestionTextareaField.tsx, frontend/src/components/question-service/edit-question-page/QuestionTopicsField.tsx, frontend/src/components/question-service/list-question-page/FilterPopover.tsx, frontend/src/components/question-service/list-question-page/ListQuestionTable.tsx, frontend/src/components/ui/select.tsx, frontend/src/components/ui/textarea.tsx, frontend/src/index.css, frontend/src/pages/question-service/AddQuestionPage.tsx, frontend/src/pages/question-service/EditQuestionPage.tsx, frontend/src/pages/question-service/ListQuestionPage.tsx, frontend/yarn.lock
=> Implement add/edit questions page

frontend/package.json, frontend/src/App.tsx, frontend/src/api/question-service/QuestionService.ts, frontend/src/components/question-service/edit-question-page/EditQuestionForm.tsx, frontend/src/components/question-service/edit-question-page/QuestionTopicsField.tsx, frontend/src/components/question-service/list-question-page/ListQuestionTable.tsx, frontend/src/components/ui/skeleton.tsx, frontend/src/components/ui/toast.tsx, frontend/src/components/ui/toaster.tsx, frontend/src/hooks/use-toast.ts, frontend/src/pages/question-service/ListQuestionPage.tsx, frontend/tailwind.config.js, frontend/yarn.lock
For the final few bugs to fix:
- question list now shows network error message if questions cannot be loaded from backend
- added a toast notification to inform users when adding duplicate/empty topics
- added a toast notification to inform users that they are redirected to add new questions when question ID provided is invalid (e.g. http://localhost:5173/questions/definitely-something-wrong)
=> Fix remaining bugs

user-service/package-lock.json, user-service/package.json, user-service/server.ts
Fix #34
- Add proper CORS headers into user service backend
- Fix the bug that `req.body` cannot parse JSON data from the frontend properly
=> User service backend bug fix

question-service/.dockerignore, question-service/Dockerfile, question-service/README.md, question-service/package.json, user-service/.dockerignore, user-service/Dockerfile, user-service/README.MD, user-service/package.json
Add docker containerisation to question service and user service backend and also the related yarn commands
- `yarn run docker-build-image`
- `yarn run docker-create-container`
- `yarn run docker-start`
- `yarn run docker-stop`
Refer to README for more information on how to use them
#38 #39
=> Add docker containerisation to question service and user service backend

compose.yaml, matching-service/.dockerignore, matching-service/.env.example, matching-service/.gitignore, matching-service/Dockerfile, matching-service/README.md, matching-service/package-lock.json, matching-service/package.json, matching-service/src/config.ts, matching-service/src/main.ts, matching-service/src/model/MatchingManager.ts, matching-service/src/model/MatchingQueue.ts, matching-service/src/routes/MatchingRoute.ts, matching-service/tsconfig.json
Setup matching service backend, with some temporary code that will match anyone together for now (in order to test my matching frontend for now)
#48
=> Setup matching service backend

matching-service/src/model/MatchingManager.ts, matching-service/src/model/MatchingQueue.ts, matching-service/src/routes/MatchingRoute.ts
Use user's token to identify users in the matching backend instead of user id
=> Use token to identify users in the basic matching backend

frontend/src/api/user-service/UserService.ts, frontend/src/components/common/PageHeader.tsx, frontend/src/components/user-service/login-page/LoginForm.tsx, frontend/src/contexts/AuthContext.tsx
Use the token value from the backend in login response to identify users in the frontend
=> Use token to identify users in the frontend

compose.yaml, frontend/Dockerfile
=> Add dockerfile to frontend

frontend/src/components/common/MainContainer.tsx, frontend/src/pages/question-service/ViewQuestionPage.tsx
=> Add return to question list button for ViewQuestionPage

compose.yaml, frontend/.dockerignore, frontend/src/api/matching-service/MatchingService.ts, frontend/src/components/matching-service/StartMatchingForm.tsx, frontend/src/pages/matching-service/GetReadyPage.tsx, frontend/src/pages/matching-service/WaitForMatchingPage.tsx, matching-service/src/controllers/matchingController.ts, matching-service/src/routes/routes.ts
=> Attempt to integrate frontend to matching-service

frontend/src/api/user-service/UserService.ts, frontend/src/components/common/PageAccountNav.tsx, frontend/src/components/user-service/login-page/LoginForm.tsx, frontend/src/contexts/AuthContext.tsx, user-service/src/controllers/authController.ts
=> Add ID to AuthContext

frontend/src/api/matching-service/MatchingService.ts, frontend/src/contexts/AuthContext.tsx
Main functionality done. Fixes #93 
Things to discuss (before merging):
- How to handle expired tokens in user service (probably a nice to have) - refresh tokens?
=> Update logout function in AuthContext to remove from matching queue

frontend/src/components/user-service/signup-page/SignupForm.tsx
=> Fix bug where user credentials after signing up is wrong

collaboration-service/server.ts, frontend/src/components/matching-service/StartMatchingForm.tsx, frontend/src/pages/collaboration-service/CollaborationPage.tsx, frontend/src/pages/matching-service/WaitForMatchingPage.tsx
=> Fix page transitioning (between matching and collab pages), where there was an awkward intermediate page

frontend/src/api/matching-service/MatchingService.ts, frontend/src/components/matching-service/ProgLangField.tsx, frontend/src/components/matching-service/StartMatchingForm.tsx, frontend/src/pages/matching-service/GetReadyPage.tsx, frontend/src/pages/matching-service/MatchingFailedPage.tsx, frontend/src/pages/matching-service/WaitForMatchingPage.tsx, matching-service/src/controllers/matchingController.ts, matching-service/src/model/user.ts, matching-service/src/routes/matchingRoute.ts
Users are now matched with an additional criteria
This only includes the matching logic, I did not edit any logic in collab service
=> [Matching Service]: Add new programming language selection for matching

collaboration-service/src/routes/collabRoute.ts, collaboration-service/src/utils/collabStore.ts, frontend/src/api/collaboration-service/CollaborationService.ts, frontend/src/api/question-service/Question.ts, frontend/src/components/collaboration-service/CodeEditingArea.tsx, frontend/src/components/collaboration-service/ProgrammingLanguages.ts, frontend/src/components/collaboration-service/QuestionArea.tsx, frontend/src/pages/collaboration-service/CollaborationPage.tsx, frontend/src/pages/collaboration-service/LanguageScripts.ts, question-service/src/models/questionModel.ts
what I have done:
1. When user changes language, `collabStore` is updated for both users
2. change `Question` to have `testInputs` and `testOutputs` fields
3. Only python and javascript supported (for now)
PS:
1. questions that do not have any testInputs/testOutputs should be an empty array: []
1.1 only questions 98 and 99 currently have proper testInputs/testOutputs
=> N3 - when user runs code, code is executed against test cases

frontend/src/components/collaboration-service/CodeEditingArea.tsx, frontend/src/components/collaboration-service/LayoutManager.tsx, frontend/src/pages/collaboration-service/CollaborationPage.tsx
=> Move end session and run code buttons in collab service

frontend/src/components/collaboration-service/CodeEditingArea.tsx, frontend/src/components/collaboration-service/QuestionArea.tsx
Change test cases to show number of test cases passed, instead of individual test cases
=> Milestone N3 - code execution

collaboration-service/server.ts, collaboration-service/src/chat/chatbotController.ts, frontend/src/components/collaboration-service/communication/ChatBubble.tsx, frontend/src/components/collaboration-service/communication/ChatPanel.tsx
=> Add code context for AI chat feature

collaboration-service/server.ts, frontend/src/components/collaboration-service/CodeEditingArea.tsx, frontend/src/components/collaboration-service/QuestionArea.tsx, frontend/src/components/collaboration-service/TestCaseResults.tsx, frontend/src/components/ui/button.tsx, frontend/src/contexts/CollaborationContext.tsx, frontend/src/pages/collaboration-service/CollaborationPage.tsx
1. refactored `QuestionArea.tsx` to contain child component `TestCaseResults.tsx`
2. Change `CollabPage` to have 2 buttons: `run-code` and `submit-code`
3. Fix bug #122 with `useRef`
=> Run code button

frontend/src/components/collaboration-service/TestCaseResults.tsx, frontend/src/pages/collaboration-service/CollaborationPage.tsx
=> Fix whitescreen bug in collab
